Update AllJoyn packages to pull source tarballs from Jenkins builds.
Change-Id: I28860807ddf1e5b46d559ddb2cdfffb2e328d7b4
Signed-off-by: Steve Kinneberg <stevek@qce.qualcomm.com>

diff --git a/alljoyn-onboarding/files/wifi_mgmt b/alljoyn-onboarding/files/wifi_mgmt
--- a/alljoyn-onboarding/files/wifi_mgmt
+++ b/alljoyn-onboarding/files/wifi_mgmt
@@ -27,51 +27,65 @@ ERROR_UNAUTHORIZED=3
 ERROR_GENERAL=4
 
 WPA_CLI() {
-	local iface=$1;shift
-	local opt
-	case ${iface} in
-		global) opt="-g /var/run/wpa_supplicant-${iface}" ;;
-		*) opt="-p /var/run/wpa_supplicant-${iface} -i ${iface}";;
-	esac
-	if [ -n "${DEBUG}" ]; then
-		echo wpa_cli ${opt} "$@" >&2
-		wpa_cli ${opt} "$@" || exit 2
-		return 0
-	fi
-	wpa_cli ${opt} "$@" >/dev/null 2>&1 || exit 2
+    local iface=$1;shift
+    local opt
+    case ${iface} in
+        global) opt="-g /var/run/wpa_supplicant-${iface}" ;;
+        *) opt="-p /var/run/wpa_supplicant-${iface} -i ${iface}";;
+    esac
+    if [ -n "${DEBUG}" ]; then
+        echo wpa_cli ${opt} "$@" >&2
+        wpa_cli ${opt} "$@" || exit 2
+        return 0
+    fi
+    wpa_cli ${opt} "$@" >/dev/null 2>&1 || exit 2
 }
 
 wifi_connect() {
-	local ssid=$(uci get alljoyn-onboarding.@onboarding[0].ssid)
-	local encryption=$(uci get alljoyn-onboarding.@onboarding[0].encryption)
-	local key=$(uci get alljoyn-onboarding.@onboarding[0].key)
+    local ssid=$(uci get alljoyn-onboarding.@onboarding[0].ssid)
+    local encryption=$(uci get alljoyn-onboarding.@onboarding[0].encryption)
+    local key=$(uci get alljoyn-onboarding.@onboarding[0].key)
 
-	if [ "$encryption" = "wep" ]; then
-		local getwepkey="uci get alljoyn-onboarding.@onboarding[0].key$key"
-		local wepkey=$($getwepkey)
-		local setwepkey="uci set wireless.@wifi-iface[0].key$key=$wepkey"
-		$setwepkey
-	fi
-	uci set wireless.@wifi-iface[0].mode=sta
-	uci set wireless.@wifi-iface[0].network=obswifi
-	uci set wireless.@wifi-iface[0].ssid="$ssid"
-	uci set wireless.@wifi-iface[0].key="$key"
-	uci set wireless.@wifi-iface[0].encryption=$encryption
-	uci commit wireless
-	wifi
+    if [ "$encryption" = "wep" ]; then
+        local getwepkey="uci get alljoyn-onboarding.@onboarding[0].key$key"
+        uci set wireless.@wifi-iface[0].key$key="$($getwepkey)"
+    fi
+
+    uci set wireless.@wifi-iface[0].mode=sta
+    uci set wireless.@wifi-iface[0].network=obswifi
+    uci set wireless.@wifi-iface[0].ssid="$ssid"
+    uci set wireless.@wifi-iface[0].key="$key"
+    uci set wireless.@wifi-iface[0].encryption=$encryption
+    uci delete wireless.@wifi-iface[0].hidden
+    uci commit wireless
+    wifi
+
+# when in station mode, set the scan_wifi cron job to run every hour
+    /etc/init.d/cron stop
+    sed -i '/\/usr\/sbin\/wifi_scan/d' /etc/crontabs/root
+    echo '1 * * * * /usr/sbin/wifi_scan' >> /etc/crontabs/root
+    /etc/init.d/cron start
 }
 
 wifi_softap() {
     local ssid=$(uci get alljoyn-onboarding.@onboarding[0].apssid)
     local encryption=$(uci get alljoyn-onboarding.@onboarding[0].apencryption)
     local key=$(uci get alljoyn-onboarding.@onboarding[0].apkey)
+    local hidden=$(uci get alljoyn-onboarding.@onboarding[0].aphidden)
     uci set wireless.@wifi-iface[0].mode=ap
     uci set wireless.@wifi-iface[0].network=lan
     uci set wireless.@wifi-iface[0].ssid="$ssid"
     uci set wireless.@wifi-iface[0].key="$key"
     uci set wireless.@wifi-iface[0].encryption=$encryption
+    uci set wireless.@wifi-iface[0].hidden=$hidden
     uci commit wireless
     wifi
+
+# when in soft ap mode, set the scan_wifi cron job to run every 15 minutes
+    /etc/init.d/cron stop
+    sed -i '/\/usr\/sbin\/wifi_scan/d' /etc/crontabs/root
+    echo '*/15 * * * * /usr/sbin/wifi_scan' >> /etc/crontabs/root
+    /etc/init.d/cron start
 }
 
 wifi_reset() {
@@ -79,55 +93,53 @@ wifi_reset() {
 }
 
 wifi_configure_commit() {
-	uci set alljoyn-onboarding.@onboarding[0].ssid="$1"
-	uci set alljoyn-onboarding.@onboarding[0].encryption=$2
-	if [ "$2" = "wep" ]; then
-		uci set alljoyn-onboarding.@onboarding[0].key="$4"
-		local setkey="uci set alljoyn-onboarding.@onboarding[0].key$4=$3"
-		$setkey
-	else
-		uci set alljoyn-onboarding.@onboarding[0].key="$3"
-	fi
-	uci commit alljoyn-onboarding
+    uci set alljoyn-onboarding.@onboarding[0].ssid="$1"
+    uci set alljoyn-onboarding.@onboarding[0].encryption="$2"
+    if [ "$2" = "wep" ]; then
+        uci set alljoyn-onboarding.@onboarding[0].key="$5"
+        uci set alljoyn-onboarding.@onboarding[0].key$5="$4"
+    else
+        uci set alljoyn-onboarding.@onboarding[0].key="$3"
+    fi
+    uci commit alljoyn-onboarding
 }
 
 wifi_connect_status() {
-	ifstatus=$(ifstatus obswifi)
-	json_load "$ifstatus"
-	json_get_var iface device
-	local timeout=4
-	local result=$ERROR_UNREACHABLE
-	local conn_state=0
-	while [ ${timeout} -gt 0 ]; do
-		sleep 1
-		conn_state=$(wpa_cli -i ${iface} status 2>/dev/null | grep wpa_state | cut -d= -f2)
-		echo ${conn_state} >&2
-		if [ ${conn_state} = "COMPLETED" ]; then
-			result=$ERROR_NONE
-			set_error $ERROR_NONE "Validated"
-			return $result
-		elif [ ${conn_state} = "SCANNING" ]; then
-			result=$ERROR_UNREACHABLE
-			set_error $ERROR_UNREACHABLE "Unreachable"
-		elif [ ${conn_state} = "4WAY_HANDSHAKE" ]; then
-			set_error $ERROR_UNAUTHORIZED "Unauthorized - 4WAY_HANDSHAKE timeout"
-			result=$ERROR_UNAUTHORIZED
-		elif [ ${conn_state} = "DISCONNECTED" ]; then
-			set_error $ERROR_UNAUTHORIZED "Unauthorized - DISCONNECTED"
-			result=$ERROR_UNAUTHORIZED
-		else
-			result=$ERROR_PROTOCOL
-			set_error $ERROR_PROTOCOL "Unsupported protocol"
-		fi
-		timeout=$((--timeout))
-	done
+    iface=`iw dev | grep Interface | cut -f 2 -s -d" "`
+    local timeout=4
+    local result=$ERROR_UNREACHABLE
+    local conn_state=0
+    while [ ${timeout} -gt 0 ]; do
+        sleep 1
+        conn_state=$(wpa_cli -i ${iface} status 2>/dev/null | grep wpa_state | cut -d= -f2)
+        echo ${conn_state} >&2
+        if [ "${conn_state}" = "COMPLETED" ]; then
+            result=$ERROR_NONE
+            set_error $ERROR_NONE "Validated"
+            return $result
+        elif [ "${conn_state}" = "SCANNING" ]; then
+            result=$ERROR_UNREACHABLE
+            set_error $ERROR_UNREACHABLE "Unreachable"
+        elif [ "${conn_state}" = "4WAY_HANDSHAKE" ]; then
+            set_error $ERROR_UNAUTHORIZED "Unauthorized - 4WAY_HANDSHAKE timeout"
+            result=$ERROR_UNAUTHORIZED
+        elif [ "${conn_state}" = "DISCONNECTED" ]; then
+            set_error $ERROR_UNAUTHORIZED "Unauthorized - DISCONNECTED"
+            result=$ERROR_UNAUTHORIZED
+        else
+            result=$ERROR_PROTOCOL
+            set_error $ERROR_PROTOCOL "Unsupported protocol"
+            echo "wpa_cli returned unknown status" >&2
+        fi
+        timeout=$((--timeout))
+    done
 
-	echo "Timeout --> unreachable" >&2
-	return $result
+    echo "Timeout --> unreachable" >&2
+    return $result
 }
 
 showhelp() {
-	cat << EOF
+    cat << EOF
   $0 -s <ssid> -a <auth>
      [-p <passphrase>] [-k key] [-i index] [ -t timeout ] [ -d ]
 
@@ -156,62 +168,62 @@ EOF
 
 check_params() {
     local ssid=$1
-	local auth=$2
-	local psk=$3
-	local key=$4
-	local index=$5
+    local auth=$2
+    local psk=$3
+    local key=$4
+    local index=$5
 
-	if [ -z "${auth}" ] || [ -z "${ssid}" ]; then
-		echo "Error:ssid or authentication not found" >&2
-		return 1
-	fi
+    if [ -z "${auth}" ] || [ -z "${ssid}" ]; then
+        echo "Error:ssid or authentication not found" >&2
+        return 1
+    fi
 
-	# Using passphrase and/or key and/or index in Open mode is inconsistent
-	if [ "${auth}" = "open" ]; then
-		if [ -n "${key}" -o -n "${index}" -o -n "${psk}" ]; then
-			echo "Open mode can't be used with passphrase/key/index" >&2
-			return 1
-		fi
-	fi
+    # Using passphrase and/or key and/or index in Open mode is inconsistent
+    if [ "${auth}" = "open" ]; then
+        if [ -n "${key}" -o -n "${index}" -o -n "${psk}" ]; then
+            echo "Open mode can't be used with passphrase/key/index" >&2
+            return 1
+        fi
+    fi
 
-	# If wep is used, make sure we also got a key & its index
-	if [ "${auth}" = "wep" ]; then
-		if [ -z "${key}" ]; then
-			echo "In WEP, please specify the key and optionally, the index" >&2
-			return 1
-		fi
-	fi
+    # If wep is used, make sure we also got a key & its index
+    if [ "${auth}" = "wep" ]; then
+        if [ -z "${key}" ]; then
+            echo "In WEP, please specify the key and optionally, the index" >&2
+            return 1
+        fi
+    fi
 
-	# Having a key and/or index with non-WEP encryption is inconsistent
-	if [ "${auth}" != "wep" ]; then
-		if [ -n "${key}" -o -n "${index}" ]; then
-			echo "Index/Key can't be used with non-WEP authentication " >&2
-                	return 1
-		fi
-	fi
+    # Having a key and/or index with non-WEP encryption is inconsistent
+    if [ "${auth}" != "wep" ]; then
+        if [ -n "${key}" -o -n "${index}" ]; then
+            echo "Index/Key can't be used with non-WEP authentication " >&2
+                    return 1
+        fi
+    fi
 
-	# If wpa is used, make sure we also got a passphrase
-	case "$auth" in 
-		*psk*)
-		if [ -z "${psk}" ]; then
-			echo "In WPA, please specify a passphrase" >&2
-			return 1
-		fi
+    # If wpa is used, make sure we also got a passphrase
+    case "$auth" in 
+        *psk*)
+        if [ -z "${psk}" ]; then
+            echo "In WPA, please specify a passphrase" >&2
+            return 1
+        fi
 
-        	if [ $(expr length "${psk}") -lt 8 ]; then
-			echo "In WPA, please specify a passphrase of size at least 8" >&2
-            		return 1
-        	fi
+            if [ $(expr length "${psk}") -lt 8 ]; then
+            echo "In WPA, please specify a passphrase of size at least 8" >&2
+                    return 1
+            fi
 
-        	if [ $(expr length "${psk}") -gt 63 ]; then
-			echo "In WPA, please specify a passphrase of size less than 64" >&2
-            		return 1
-        	fi
-		;;
-		*)
-	esac
+            if [ $(expr length "${psk}") -gt 63 ]; then
+            echo "In WPA, please specify a passphrase of size less than 64" >&2
+                    return 1
+            fi
+        ;;
+        *)
+    esac
 
-	return 0
+    return 0
 }
 
 wifi_configure() {
@@ -219,77 +231,79 @@ wifi_configure() {
 local ssid auth psk key index
 
 while [ -n "$1" ];do
-	case "$1" in
-	-s) ssid=$2; shift;;
-	-a) auth=$2; shift
+    case "$1" in
+    -s) ssid="$2"; shift;;
+    -a) auth="$2"; shift
 
-		if [ "${auth}" = "OPEN" ]; then
-			auth="none"
-		fi
+        if [ "${auth}" = "OPEN" ]; then
+            auth="none"
+        fi
 
-		if [ "${auth}" = "WEP" ]; then
-			auth="wep"
-		fi
+        if [ "${auth}" = "WEP" ]; then
+            auth="wep"
+        fi
 
-		case "$auth" in 
-		WPA2*)
-			auth="psk2+tkip+ccmp"
-			;;
-		WPA*)
-			auth="psk+tkip+ccmp"
-			;;
-		esac
+        case "$auth" in 
+        WPA2*)
+            auth="psk2+tkip+ccmp"
+            ;;
+        WPA*)
+            auth="psk+tkip+ccmp"
+            ;;
+        esac
 
-		if [ "${auth}" = "WPS" ]; then
-			auth="psk"
-		fi
+        if [ "${auth}" = "WPS" ]; then
+            auth="psk"
+        fi
 
-		[ ${auth} = "none" ] || [ ${auth} = "wep" ] || [ ${auth} = "psk+tkip+ccmp" ] || [ ${auth} = "psk2+tkip+ccmp" ] || {
-			echo "Invalid authentication \"${auth}\"" >&2
-			echo "Valid authentication values are \"none\", \"wep\", \"psk+tkip+ccmp\", \"psk2+tkip+ccmp\"" >&2
-			showhelp
-			exit 2;
-		};;
-	-p) psk=$2; shift;;
-	-k) key=$2; shift;;
-	-i) index=$2; shift
-		if [ ! ${index} -ge 1 ] && [ ! ${index} -le 4 ]; then
-			echo "Invalid index \"${index}\"" >&2
-			echo "Valid index values are \"1\", \"2\", \"3\", \"4\"" >&2
-			showhelp
-			exit 2
-		fi;;
-	-t) timeout=$2; shift;;
-	-d) DEBUG=1;;
-	-h) showhelp; exit 2;;
-	*)
-		echo "Invalid option: -${OPTARG}" >&2
-		showhelp
-		exit 2
-		;;
-	esac
-	shift
+        [ ${auth} = "none" ] || [ ${auth} = "wep" ] || [ ${auth} = "psk+tkip+ccmp" ] || [ ${auth} = "psk2+tkip+ccmp" ] || {
+            echo "Invalid authentication \"${auth}\"" >&2
+            echo "Valid authentication values are \"none\", \"wep\", \"psk+tkip+ccmp\", \"psk2+tkip+ccmp\"" >&2
+            showhelp
+            exit 2;
+        };;
+    -p) psk="$2"; shift;;
+    -k) key="$2"; shift;;
+    -i) index="$2"; shift
+        if [ ! ${index} -ge 1 ] && [ ! ${index} -le 4 ]; then
+            echo "Invalid index \"${index}\"" >&2
+            echo "Valid index values are \"1\", \"2\", \"3\", \"4\"" >&2
+            showhelp
+            exit 2
+        fi;;
+    -t) timeout="$2"; shift;;
+    -d) DEBUG=1;;
+    -h) showhelp; exit 2;;
+    *)
+        echo "Invalid option: -${OPTARG}" >&2
+        showhelp
+        exit 2
+        ;;
+    esac
+    shift
 done
 
 if [ "${auth}" = "wep" ]; then
-	if [ -z "${index}" ]; then
-		index=1
-		echo "Defaulting index to 1" >&2
-	fi
+    if [ -z "${index}" ]; then
+        index=1
+        echo "Defaulting index to 1" >&2
+    fi
 fi
 
 # Perform sanity checks on the script arguments
 check_params "${ssid}" "${auth}" "${psk}" "${key}" "${index}" || {
-	showhelp
-	exit 2
+    showhelp
+    exit 2
 }
 
-wifi_configure_commit "${ssid}" ${auth} ${psk} ${key} ${index}
+
+
+wifi_configure_commit "${ssid}" "${auth}" "${psk}" "${key}" "${index}"
 }
 
 set_error() {
-	uci set alljoyn-onboarding.@onboarding[0].lasterrorcode=$1
-	uci set alljoyn-onboarding.@onboarding[0].lasterrormsg="$2"
-	uci commit alljoyn-onboarding
-	printf '%s\n%s' "$1" "$2" > /tmp/state/alljoyn-onboarding-lasterror
+    uci set -c /etc/alljoyn-onboarding alljoyn-onboarding-state.@onboarding[0].lasterrorcode=$1
+    uci set -c /etc/alljoyn-onboarding alljoyn-onboarding-state.@onboarding[0].lasterrormsg="$2"
+    uci commit -c /etc/alljoyn-onboarding alljoyn-onboarding-state
+    printf '%s\n%s' "$1" "$2" > /tmp/state/alljoyn-onboarding-lasterror
 }
